paths:
  aoi_root: "../AOI"
  config_dir: "config"

  tnc_aoi_shapefile: "../AOI/TNC_AOI_LayerPkg/TNC_AOIs.shp"

  north_cache_root: "../AOI/NorthAOI/GWNF_cache_3_4"
  south_cache_root: "../AOI/SouthAOI/Smoky_cache_3_4"

  north_index_cache_root: "../AOI/NorthAOI/GWNF_cache_3_4/s2/indices"
  south_index_cache_root: "../AOI/SouthAOI/Smoky_cache_3_4/s2/indices"

  north_landsat_index_root: "../AOI/NorthAOI/GWNF_cache_3_4/landsat/indices"
  south_landsat_index_root: "../AOI/SouthAOI/Smoky_cache_3_4/landsat/indices"

  north_terrain_dir: "../AOI/NorthAOI/GWNF_cache_3_4/s2/traits/terrain"
  south_terrain_dir: "../AOI/SouthAOI/Smoky_cache_3_4/s2/traits/terrain"

  north_forest_group_dir: "../AOI/NorthAOI/GWNF_cache_3_4/s2/traits/forest/forest_type_group"
  south_forest_group_dir: "../AOI/SouthAOI/Smoky_cache_3_4/s2/traits/forest/forest_type_group"

  north_forest_type_dir: "../AOI/NorthAOI/GWNF_cache_3_4/s2/traits/forest/forest_type_type"
  south_forest_type_dir: "../AOI/SouthAOI/Smoky_cache_3_4/s2/traits/forest/forest_type_type"

  north_ecozone_dir: "../AOI/NorthAOI/GWNF_cache_3_4/s2/traits/ecozone"
  south_ecozone_dir: "../AOI/SouthAOI/Smoky_cache_3_4/s2/traits/ecozone"

  north_species_raster: "../AOI/NorthAOI/GWNF_cache_3_4/s2/traits/forest/forest_type_type/forest_type_type.tif"
  south_species_raster: "../AOI/SouthAOI/Smoky_cache_3_4/s2/traits/forest/forest_type_type/forest_type_type.tif"

  north_raw_ecozone_raster: "../AOI/NorthAOI/GWNF_cache_3_4/s2/traits/ecozone/tnc_ecozone_simplified_north/fortype_aoiN.tif"
  south_raw_ecozone_raster: "../AOI/SouthAOI/Smoky_cache_3_4/s2/traits/ecozone/tnc_ecozone_simplified_south/fortype_aois.tif"

  conus_forest_group_img: "../AOI/NorthAOI/GWNF_cache_3_4/s2/traits/forest/forest_type_group/conus_forestgroup.img"
  conus_forest_type_img: "../AOI/NorthAOI/GWNF_cache_3_4/s2/traits/forest/forest_type_type/conus_foresttype.img"

  results_figures_dir: "Results/figures"
  results_rasters_dir: "Results/rasters"
  results_tables_dir:  "Results/tables"

  results_figures_landsat_dir: "Results/figures/landsat"
  results_tables_landsat_dir:  "Results/tables/landsat"
  landsat_annual_max_dir:      "Results/rasters/landsat_annual_max"
  landsat_anomaly_dir:         "Results/rasters/landsat_anomaly"

  monthly_max_dir:             "Results/rasters/monthly_max"
  landsat_monthly_max_dir:     "Results/rasters/landsat_monthly_max"
